name: BuildTestServer

on:
  workflow_dispatch:
    branches: [master, develop]

jobs:
  testserver:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: "{{defaultContext}}:tests/testserver"
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-testserver:latest
